#pragma once

#define PERMISSIVE_HOLD
#define RGBLIGHT_STATIC_PATTERNS

// #define DISABLE_RGB_MATRIX_DIGITAL_RAIN
// #define DISABLE_RGB_MATRIX_ALPHAS_MODS
// #define DISABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
// #define DISABLE_RGB_MATRIX_RAINDROPS
#define RGB_MATRIX_STARTUP_SPD 60
#define TAPPING_TERM 150
