#pragma once

#define MK_MOMENTARY_ACCEL
#define MK_COMBINED
#define PERMISSIVE_HOLD

//#define DISABLE_RGB_MATRIX_DIGITAL_RAIN
//#define DISABLE_RGB_MATRIX_ALPHAS_MODS
//#define DISABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
//#define DISABLE_RGB_MATRIX_RAINDROPS
#define RGB_MATRIX_STARTUP_SPD 60
#define TAPPING_TERM 150
